# Generated by Django 5.2.5 on 2025-08-25 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(default=django.utils.timezone.now)),
                ('draw_date', models.DateField()),
                ('model_type', models.CharField(choices=[('frequency', 'Frequency Model'), ('pattern', 'Pattern Model'), ('clustering', 'Clustering Model'), ('regression', 'Regression Model'), ('neural', 'Neural Network Model'), ('time_series', 'Time Series Model'), ('ensemble', 'Ensemble Model'), ('bayesian', 'Bayesian Model')], max_length=20)),
                ('number_1', models.IntegerField()),
                ('number_2', models.IntegerField()),
                ('number_3', models.IntegerField()),
                ('number_4', models.IntegerField()),
                ('number_5', models.IntegerField()),
                ('powerball', models.IntegerField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotteryDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField()),
                ('draw_number', models.IntegerField(blank=True, null=True)),
                ('number_1', models.IntegerField()),
                ('number_2', models.IntegerField()),
                ('number_3', models.IntegerField()),
                ('number_4', models.IntegerField()),
                ('number_5', models.IntegerField()),
                ('powerball', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-draw_date'],
                'unique_together': {('draw_date', 'draw_number')},
            },
        ),
        migrations.CreateModel(
            name='PredictionAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_numbers_matched', models.IntegerField(default=0)),
                ('powerball_matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predictor.lotterydraw')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.prediction')),
            ],
        ),
    ]
